exports.createLandmineBelow  = function () {
  //Instantiations;
  var block;
  var data;
  var sign;
  var state;
  var start;
  block = server.worlds[0].getHighestBlockAt (self.location);
  location = block.location;
  location=location.add (0,-2,0);
  start = location;  
  console.log ("Create landmine at:" + location);
  server.worlds[0].getBlockAt (location).setType (org.bukkit.Material.REPEATING_COMMAND_BLOCK);
  block = server.worlds[0].getBlockAt (location);
  state = block.getState();
  state.setCommand("execute if entity @p[distance=..4] run setblock ~4 ~ ~ redstone_block");
  state.update();
  location=location.add (1,0,0);
  server.worlds[0].getBlockAt (location).setType (org.bukkit.Material.REDSTONE_BLOCK);
  location=location.add (2,0,0);
  server.worlds[0].getBlockAt (location).setType (org.bukkit.Material.COMMAND_BLOCK);
  block = server.worlds[0].getBlockAt (location);
  state = block.getState();
  state.setCommand("summon tnt ~-3 ~7 ~ {fuse:0}");
  state.update();
  location=location.add (2,0,0);
  server.worlds[0].getBlockAt (location).setType (org.bukkit.Material.COMMAND_BLOCK);
  cmd="fill " + (start.x-5) + " " + (start.y+1) + " " + start.z + " " + (start.x + 1) + " " + start.y + " " + start.z + " air replace";
  console.log (cmd);
  block = server.worlds[0].getBlockAt (location);
  state = block.getState();
  state.setCommand(cmd);
  state.update();
};